name: test website build
on:
  pull_request:
    branches: 
      - main

jobs:
  test-build:
    runs-on: ubuntu-24.04
    steps:

      # Check out the code
      - name: Checkout main branch
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Test building the website
      - name: Build website
        run: mkdocs build --strict
